eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:admin@registry/eureka/
spring:
  rabbitmq:
    host: rabbitmq
    username: penghong
    password: 123123ph@Rm
user:
  name: ph
management:
  security:
    enabled: false
info:
  app-name: ${spring.application.name}
  company-name: ngos
  build.version: ${spring.application.version}