eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:admin@registry/eureka/
spring:
  rabbitmq:
    host: rabbitmq
    username: penghong
    password: 123123ph@Rm
  zipkin:
    base-url: http://localhost:85
  sleuth:
    sampler:
      percentage: 1.0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.20.19.116:3309/spring-cloud-auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
user:
  name: ph
info:
  app-name: ${spring.application.name}
  company-name: ngos
  build.version: ${spring.application.version}