logging:
  level:
    org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter: error
server:
  port: 83
turbine:
  stream:
    port: 8041
spring:
  rabbitmq:
    host: rabbitmq
    username: penghong
    password: 123123ph@Rm
  boot:
    admin:
      username: user
      password: admin
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: http://monitor:${turbine.stream.port}
info:
  app:
    name: monitor-service
  company:
    name: ngos
  build:
    artifactId: @project.artifactId@
    version: @project.version@
management:
  security:
    enabled: false