server:
  port: 89

name: zhangxd

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.20.19.116:3309/spring-cloud-auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
security:
  oauth2:
    resource:
      # 获取当前Token的用户信息
      user-info-uri: http://localhost:84/user/current
    client:
      clientId: svca
      clientSecret: svca
      # 获取Token
      accessTokenUri: http://localhost:84/oauth/token
      #grant-type: client_credentials
      scope: read

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000 #断路器超时时间，默认1000ms