server:
  port: 89

name: zhangxd

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.20.19.116:3309/spring-cloud-auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
security:
  oauth2:
    resource:
      # 获取当前Token的用户信息
      user-info-uri: http://localhost:84/user/current
    client:
      clientId: user
      clientSecret: user
      # 获取Token
      accessTokenUri: http://localhost:84/oauth/token
      grant-type: client_credentials,password
      scope: server
