spring:
  application:
    name: zipkin
  rabbitmq:
    host: rabbitmq
    username: penghong
    password: 123123ph@Rm
server:
  port: 9411

security:
  user:
    name: admin
    password: ${ZIPKIN_SERVER_PASSWORD:admin}
